---
title: "Atlas Aquatica"
format: gfm
---

Since the invention of SCUBA in 1942, diving tourism has evolved from a niche activity to a thriving industry that lures practitioners with the promise of experiencing wildlife encounters from every corner of the world. Therefore, mapping dive sites and engaging the diving sector in conservation frameworks directly contribute to mapping and protecting associated marine ecosystems and their contributions to people. A global map of dive sites, with the associated information of tourism operators offering such activities, can galvanize a network of divers and operators that has a high potential for citizen science, collective actions towards conservation, and a better understanding of the economic benefits of marine ecosystems. Such integration of divers in conservation can directly help to protect critical ecosystems, such as coral reefs, as well as establishing marine protected areas around diving sites. Improvement in environmental protection in those diving sites can also co-benefit other sectors like fisheries and other sections of the overall tourism industry and coastal infrastructure. This global network can become a platform to promote the centralization and flow of information to all stakeholders. Those dive sites, once their true value is recognized, can be beacons around which effective and equitable environmental protection is put in place through tools like Marine Protected Areas, other effective conservation measures (OECMs), and the creation of Indigenous and community conserved areas and territories (ICCAs) and locally managed marine areas (LMMAs).

Economic value from given industries can be estimated in various ways, but we focus here on the direct economic impact (i.e., gross revenue) of marine dive tourism per year around the world. These are real expenditures made by participants in diving activities with scuba and snorkel operators; ideally, total economic impacts including additional rounds of spending would be included, but the information necessary for this type of analysis is not available for most parts of the world and so would require strong assumptions. This analysis requires 1) a global list of existing dive operators and locations; 2) survey data on participation, expenditures, and employment generated per year; and 3) a meta-analytical model to fill missing gaps in information. The initial global list of dive operators is essential because it represents all individual data points for which expenditures are calculated. Fortunately for this context, the vast majority of dive activities around the world are led and promoted by operators affiliated with one of few certifying bodies, the largest of which, PADI, has over 50% global market share and 70% in the USA (others include NAUI, SSI, and SDI).

Given our knowledge of pertinent prior research and available data and our existing relationships with dive centers and associations around the world, we anticipate a highly representative survey sample. However, it is important to anticipate and address data uncertainty and sensitivity in results given the large scope of the analysis and likely variations in available data for different regions of the world. In the first-best case, we will have direct (survey) information on an operator and the average yearly (by season) number of participants (divers, and snorkelers), expenditures (gross revenue), and employment (full-time equivalents as proportion of revenue). When one or more of these parameters are not available, they will be estimated using a stepwise value-transfer approach.

Similar methodologies have been used, for example, in global estimates of recreational fishing (1) and shark watching expenditures (2), economic impacts from commercial fisheries (3), and regional estimates of ecotourism expenditures (4). For a missing value, we anticipate using median values from operators with available data within the same city, municipality, state (or equivalent), country, subregion, or region, as available (based on prior research, it is very unlikely that regional values will have to be used). Jackknife resampling will be used to determine sensitivity and to provide confidence bounds for the results of the meta-analysis (5). In addition to showing aggregate totals, we anticipate developing a global map showing the locations and available data for dive operators, and a global heatmap for each of our variables (participation, expenditures, employment). The latter is done in part to protect confidentiality of individual responses from operators, and all of their survey responses will be kept separately from their identifying information in secure databases.

Our endeavor, the Atlas Aquatica, in collaboration with the University of British Columbia and the Scripps Institution of Oceanography, University of California, San Diego, will detail the distribution of the diving sites on a global level, organize a
database with socioeconomic and ecological data associated with the diving
sites, identify gaps in knowledge as well as important hotspots and conservation opportunities. All this information will be updated on an online platform which will be used as the main interface for users (e.g., stakeholder) to view data assembled in this project.

### Goal 

To generate the first comprehensive map of diving sites at a global level,
including key associated ecological, biological, and socioeconomic data that
can connect all stakeholders and inform improved conservation and marine
spatial planning.

#### Objectives

-   Engage stakeholders and experts to identify key potential information and data gaps

-   Create a data platform and identify information gaps, hotspots, and conservation opportunities

-   Form a global network of collaborations that will aid in developing a plan to insert the diving industry as a major player to help fulfill the Sustainable
    Development Goals (SDG) and protect marine biodiversity.

#### Activities

Build the diving site database by sourcing all the available information (web-scraping) worldwide that can be used to obtain or reconstruct a georeferenced list of the diving sites.

Regularly update the database and store it in dataMares.

Conduct surveys with participants and diver operators regarding participation, expenditures, local income, employment for *Africa, Europe, and Oceania.*

Conduct literature reviews on economic analyses conducted on diving related activities on local and global scales for *Africa, the Americas, Asia, Europe, and Oceania.*

Sequester public agency and private statistics of the diving industry.

[***Outputs***]{.underline}

1.  Survey and literature review data on participation, expenditures, and employment generated per year by marine dive operators and sites for *Africa, the Americas, Asia, Europe, and Oceania.*

2.  Estimates of yearly participation, expenditures, and employment generated by the marine dive industry for *Africa, the Americas, Asia, Europe, and Oceania.* A list of existing dive operators and locations in *Africa, the Americas, Asia, Europe, and Oceania.*

3.  A model considering direct estimates, meta-analyses, ground-truthing, and sensitivity analyses that summarize economic benefits of dive tourism, as well as a meta-analytic model to fill missing gaps in information.

4.  Publication regarding the economic valuation of dive operations.

    #### References

    1\. Cisneros-Montemayor AM, Sumaila UR. A global
    estimate of benefits from ecosystem-based marine recreation: potential impacts
    and implications for management. J Bioeconomics. 2010;12(3):245--268.

    2\. Cisneros-Montemayor AM, Barnes-Mauthe M, Al-Abdulrazzak D,
    Navarro-Holm E, Sumaila UR. Global economic value of shark ecotourism:
    implications for conservation. Oryx. 2013 May 30;47(03):381--8.

    3\. Dyck AJ, Sumaila UR. Economic impact of ocean fish populations in
    the global fishery. J Bioeconomics. 2010 Aug 19;12(3):227--43.

    4\. Cisneros‐Montemayor AM, Townsel A, Gonzales CM, Haas AR,
    Navarro‐Holm EE, Salorio‐Zuñiga T, et al. Nature‐based marine tourism in the
    Gulf of California and Baja California Peninsula: Economic benefits and key
    species. Nat Resour Forum. 2020 May;44(2):111--28.

    5\. Cisneros-Montemayor AM, Pauly D, Weatherdon LV, Ota Y. A Global
    Estimate of Seafood Consumption by Coastal Indigenous Peoples. PLOS ONE. 2016
    Dec 5;11(12):e0166681.
